site_name: 'Reading NOTES'
site_url: 'https://dengyouf.github.io/fullstack-dev/'
site_author: "deng you"

repo_name: 'dengyouf/blog'
repo_url: 'https://github.com/dengyouf/fullstack-dev'

theme:
  name: readthedocs
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - HTML & CSS:
    - HTML: 'html/01_html.md'
    - CSS: 'css/01_css.md'
  - JavaScript:
    - JavaScript 基础: 'js/01-js_bases.md'
  - 前端实战:
      - 学成在线: 'css/02_css-xczx.md'

